### ISSUE TITLE
Failure to create Postgres server from script

### ISSUE THREAD

**Issue by davidimoore** [Azure-Samples/msdocs-python-django-azure-container-apps#11] opened 2023-05-06 06:00 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1.  clone the app
2.  ./create_resources.sh 

### Any log messages given by the failure
Creating PostgreSQL Server 'postgresql-db-1b3cc7' in group 'pythoncontainer-rg-1b3cc7'...
Your server 'postgresql-db-1b3cc7' is using sku 'Standard_D2s_v3' (Paid Tier). Please refer to https://aka.ms/postgres-pricing for pricing details
(MissingRequiredParameter) Parameter 'PrivateDnsZoneArmResourceId' must be specified. This parameter cannot be NULL or empty.
Code: MissingRequiredParameter
Message: Parameter 'PrivateDnsZoneArmResourceId' must be specified. This parameter cannot be NULL or empty.

### Expected/desired behavior
Successful creation of the postgresql server

### OS and Version?
>  macOS Ventura

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vmagelo** [comment] 2023-05-16 17:10
Couldn't reproduce. I ran in Windows and Linux but not in macOS.  The create_resources.sh script doesn't use --private-dns-zone for the "az postgres flexible-server create" command. 

Looking at the [docs](https://learn.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az-postgres-flexible-server-create-optional-parameters) for --private-dns-zone it says " If you want to use a zone from different resource group or subscription, please provide resource Id. CLI creates a new private dns zone within the same resource group as virtual network if not provided by users."  Is this an issue of confusion of subscriptions if you are part of more than one? Or is it temporary issue with CLI (e.g., https://github.com/Azure/azure-rest-api-specs/issues/20866)?  

Can you try again? If it doesn't work, we can open issue for "az postgres flexible-server create" directly here: https://github.com/Azure/azure-cli/issues

In fact, looking through the issues, I wonder if it's a permissions questions. This issue (https://github.com/Azure/azure-cli/issues/19322) for MySQL Flexible hints that you need reader role on subscription level.

**Comment by vmagelo** [comment] 2023-06-14 16:27
Closing for now.

**Closed by vmagelo** 2023-06-14 16:27 UTC
